### ISSUE TITLE
release-v5.0.2 not found for Sunbird-cQube/query-builder

### ISSUE THREAD

**Issue by srajasimman** [Sunbird-cQube/cqube-devops#288]
Hi @surendrasinghs @asifbasha61 

you are referencing the release tag/branch in the following line is not found.
please create a tag/branch for Sunbird-cQube/query-builder as release-v5.0.2

https://github.com/Sunbird-cQube/cqube-devops/blob/9fbb6900bdfe48ca5ace82e3d44a0d734dbb6313/shell_scripts/repository_clone.sh#L4

https://github.com/Sunbird-cQube/cqube-devops/blob/9fbb6900bdfe48ca5ace82e3d44a0d734dbb6313/shell_scripts/repository_clone.sh#L69

![image](https://github.com/Sunbird-cQube/cqube-devops/assets/15092596/c09b2ecf-fbef-45be-8421-eb5377c0db1d)

**Comment by asifbasha61** [comment]
@srajasimman Raised to the repo maintainer and the issue has been resolved now.
